name: CI

on:
  push:
    branches: 
      - master
      - integration
      - experimental*
      - release_*
  repository_dispatch:
    types:
      - metwork-trigger*

env:
    WORKFLOW_SCRIPTS_DIR: .github/workflows
    DOCKER_WORKFLOW_SCRIPTS_DIR: /src/.github/workflows
    PAYLOAD_BRANCH: ${{ github.event.client_payload.branch}}
    PAYLOAD_OS: ${{ github.event.client_payload.os}}

jobs:
  ci_build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.client_payload.branch || github.ref }}
      - name: set variables
        id: SetVariables
        run: |
          ${WORKFLOW_SCRIPTS_DIR}/set_variables.sh
      - name: debug env
        run: |
          env
          echo "Dockerfile"
          cat ./Dockerfile
      - name: docker build and push
        id: DockerStep
        env: 
          BRANCH: ${{ steps.SetVariables.outputs.branch }}
          CACHEBUST: ${{ github.run_number }}
          TAG_BRANCH: ${{ steps.SetVariables.outputs.tag_branch }}
          TAG_LATEST: ${{ steps.SetVariables.outputs.tag_latest }}
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          ${WORKFLOW_SCRIPTS_DIR}/docker_build.sh





      - name: dispatch mfserv
        if: ${{ github.event_name != 'pull_request' && steps.SetVariables.outputs.branch != 'null' && steps.DockerStep.outputs.dispatch_bypass == 'false'  && steps.SetVariables.outputs.os == 'centos8' }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.METWORK_ACCESS_TOKEN }}
          repository: metwork-framework/mfserv
          event-type: metwork-trigger-${{ steps.SetVariables.outputs.branch }}
          client-payload: '{"branch": "${{ steps.SetVariables.outputs.branch }}", "os": "centos8"}'
      - name: dispatch mfdata
        if: ${{ github.event_name != 'pull_request' && steps.SetVariables.outputs.branch != 'null' && steps.DockerStep.outputs.dispatch_bypass == 'false' && steps.SetVariables.outputs.os == 'centos8' }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.METWORK_ACCESS_TOKEN }}
          repository: metwork-framework/mfdata
          event-type: metwork-trigger-${{ steps.SetVariables.outputs.branch }}
          client-payload: '{"branch": "${{ steps.SetVariables.outputs.branch }}", "os": "centos8"}'
      - name: dispatch mfbase
        if: ${{ github.event_name != 'pull_request' && steps.SetVariables.outputs.branch != 'null' && steps.DockerStep.outputs.dispatch_bypass == 'false' && steps.SetVariables.outputs.os == 'centos8' }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.METWORK_ACCESS_TOKEN }}
          repository: metwork-framework/mfbase
          event-type: metwork-trigger-${{ steps.SetVariables.outputs.branch }}
          client-payload: '{"branch": "${{ steps.SetVariables.outputs.branch }}", "os": "centos8"}'
      - name: dispatch mfadmin
        if: ${{ github.event_name != 'pull_request' && steps.SetVariables.outputs.branch != 'null' && steps.DockerStep.outputs.dispatch_bypass == 'false' && steps.SetVariables.outputs.os == 'centos8' }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.METWORK_ACCESS_TOKEN }}
          repository: metwork-framework/mfadmin
          event-type: metwork-trigger-${{ steps.SetVariables.outputs.branch }}
          client-payload: '{"branch": "${{ steps.SetVariables.outputs.branch }}", "os": "centos8"}'
      - name: dispatch mfsysmon
        if: ${{ github.event_name != 'pull_request' && steps.SetVariables.outputs.branch != 'null' && steps.DockerStep.outputs.dispatch_bypass == 'false' && steps.SetVariables.outputs.os == 'centos8' }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.METWORK_ACCESS_TOKEN }}
          repository: metwork-framework/mfsysmon
          event-type: metwork-trigger-${{ steps.SetVariables.outputs.branch }}
          client-payload: '{"branch": "${{ steps.SetVariables.outputs.branch }}", "os": "centos8"}'
      - name: dispatch mfextaddon_scientific
        if: ${{ github.event_name != 'pull_request' && steps.SetVariables.outputs.branch != 'null' && steps.DockerStep.outputs.dispatch_bypass == 'false' && steps.SetVariables.outputs.os == 'centos8' }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.METWORK_ACCESS_TOKEN }}
          repository: metwork-framework/mfextaddon_scientific
          event-type: metwork-trigger-${{ steps.SetVariables.outputs.branch }}
          client-payload: '{"branch": "${{ steps.SetVariables.outputs.branch }}", "os": "centos8"}'
      - name: dispatch mfextaddon_mapserver
        if: ${{ github.event_name != 'pull_request' && steps.SetVariables.outputs.branch != 'null' && steps.DockerStep.outputs.dispatch_bypass == 'false' && steps.SetVariables.outputs.os == 'centos8' }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.METWORK_ACCESS_TOKEN }}
          repository: metwork-framework/mfextaddon_mapserver
          event-type: metwork-trigger-${{ steps.SetVariables.outputs.branch }}
          client-payload: '{"branch": "${{ steps.SetVariables.outputs.branch }}", "os": "centos8"}'
      - name: dispatch mfextaddon_vim
        if: ${{ github.event_name != 'pull_request' && steps.SetVariables.outputs.branch != 'null' && steps.DockerStep.outputs.dispatch_bypass == 'false' && steps.SetVariables.outputs.os == 'centos8' }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.METWORK_ACCESS_TOKEN }}
          repository: metwork-framework/mfextaddon_vim
          event-type: metwork-trigger-${{ steps.SetVariables.outputs.branch }}
          client-payload: '{"branch": "${{ steps.SetVariables.outputs.branch }}", "os": "centos8"}'
      - name: dispatch mfextaddon_rabbitmq
        if: ${{ github.event_name != 'pull_request' && steps.SetVariables.outputs.branch != 'null' && steps.DockerStep.outputs.dispatch_bypass == 'false' && steps.SetVariables.outputs.os == 'centos8' }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.METWORK_ACCESS_TOKEN }}
          repository: metwork-framework/mfextaddon_rabbitmq
          event-type: metwork-trigger-${{ steps.SetVariables.outputs.branch }}
          client-payload: '{"branch": "${{ steps.SetVariables.outputs.branch }}", "os": "centos8"}'
      - name: dispatch mfextaddon_elasticsearch
        if: ${{ github.event_name != 'pull_request' && steps.SetVariables.outputs.branch != 'null' && steps.SetVariables.outputs.branch != 'release_1.1' && steps.DockerStep.outputs.dispatch_bypass == 'false' && steps.SetVariables.outputs.os == 'centos8' }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.METWORK_ACCESS_TOKEN }}
          repository: metwork-framework/mfextaddon_elasticsearch
          event-type: metwork-trigger-${{ steps.SetVariables.outputs.branch }}
          client-payload: '{"branch": "${{ steps.SetVariables.outputs.branch }}", "os": "centos8"}'
      - name: dispatch mfextaddon_php
        if: ${{ github.event_name != 'pull_request' && steps.SetVariables.outputs.branch != 'null' && steps.SetVariables.outputs.branch != 'release_1.1' && steps.DockerStep.outputs.dispatch_bypass == 'false' && steps.SetVariables.outputs.os == 'centos8' }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.METWORK_ACCESS_TOKEN }}
          repository: metwork-framework/mfextaddon_php
          event-type: metwork-trigger-${{ steps.SetVariables.outputs.branch }}
          client-payload: '{"branch": "${{ steps.SetVariables.outputs.branch }}", "os": "centos8"}'
