name: CI

on:
  push:
    branches: 
      - master
      - integration
      - experimental*
      - release_*
  repository_dispatch:
    types:
      - metwork-trigger*

env:
    WORKFLOW_SCRIPTS_DIR: .github/workflows
    DOCKER_WORKFLOW_SCRIPTS_DIR: /src/.github/workflows
    PAYLOAD_BRANCH: ${{ github.event.client_payload.branch}}

jobs:
  ci_build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.client_payload.branch || github.ref }}
      - name: set variables
        id: SetVariables
        run: |
          ${WORKFLOW_SCRIPTS_DIR}/set_variables.sh
      - name: debug env
        run: |
          env
          echo "Dockerfile"
          cat ./Dockerfile
      - name: docker build and push
        id: DockerStep
        env: 
          BRANCH: ${{ steps.SetVariables.outputs.branch }}
          CACHEBUST: ${{ github.run_number }}
          TAG_BRANCH: ${{ steps.SetVariables.outputs.tag_branch }}
          TAG_LATEST: ${{ steps.SetVariables.outputs.tag_latest }}
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          ${WORKFLOW_SCRIPTS_DIR}/docker_build.sh

      - name: dispatch mfserv
        if: ${{ github.event_name != 'pull_request' && steps.SetVariables.outputs.branch != 'null' && steps.DockerStep.outputs.dispatch_bypass == 'false' }}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.METWORK_ACCESS_TOKEN }}
          repository: metwork-framework/mfserv
          event-type: metwork-trigger-${{ steps.SetVariables.outputs.branch }}
          client-payload: '{"branch": "${{ steps.SetVariables.outputs.branch }}"}'
      - name: dispatch mfdata
        if: ${{ github.event_name != 'pull_request' && steps.SetVariables.outputs.branch != 'null' && steps.DockerStep.outputs.dispatch_bypass == 'false' }}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.METWORK_ACCESS_TOKEN }}
          repository: metwork-framework/mfdata
          event-type: metwork-trigger-${{ steps.SetVariables.outputs.branch }}
          client-payload: '{"branch": "${{ steps.SetVariables.outputs.branch }}"}'
      - name: dispatch mfbase
        if: ${{ github.event_name != 'pull_request' && steps.SetVariables.outputs.branch != 'null' && steps.DockerStep.outputs.dispatch_bypass == 'false' }}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.METWORK_ACCESS_TOKEN }}
          repository: metwork-framework/mfbase
          event-type: metwork-trigger-${{ steps.SetVariables.outputs.branch }}
          client-payload: '{"branch": "${{ steps.SetVariables.outputs.branch }}"}'
      - name: dispatch mfadmin
        if: ${{ github.event_name != 'pull_request' && steps.SetVariables.outputs.branch != 'null' && steps.DockerStep.outputs.dispatch_bypass == 'false' }}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.METWORK_ACCESS_TOKEN }}
          repository: metwork-framework/mfadmin
          event-type: metwork-trigger-${{ steps.SetVariables.outputs.branch }}
          client-payload: '{"branch": "${{ steps.SetVariables.outputs.branch }}"}'
      - name: dispatch mfsysmon
        if: ${{ github.event_name != 'pull_request' && steps.SetVariables.outputs.branch != 'null' && steps.DockerStep.outputs.dispatch_bypass == 'false' }}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.METWORK_ACCESS_TOKEN }}
          repository: metwork-framework/mfsysmon
          event-type: metwork-trigger-${{ steps.SetVariables.outputs.branch }}
          client-payload: '{"branch": "${{ steps.SetVariables.outputs.branch }}"}'
      - name: dispatch mfextaddon_python2
        if: ${{ github.event_name != 'pull_request' && steps.SetVariables.outputs.branch != 'null' && steps.DockerStep.outputs.dispatch_bypass == 'false' }}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.METWORK_ACCESS_TOKEN }}
          repository: metwork-framework/mfextaddon_python2
          event-type: metwork-trigger-${{ steps.SetVariables.outputs.branch }}
          client-payload: '{"branch": "${{ steps.SetVariables.outputs.branch }}"}'
      - name: dispatch mfextaddon_rabbitmq
        if: ${{ github.event_name != 'pull_request' && steps.SetVariables.outputs.branch != 'null' && steps.DockerStep.outputs.dispatch_bypass == 'false' }}
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.METWORK_ACCESS_TOKEN }}
          repository: metwork-framework/mfextaddon_rabbitmq
          event-type: metwork-trigger-${{ steps.SetVariables.outputs.branch }}
          client-payload: '{"branch": "${{ steps.SetVariables.outputs.branch }}"}'



